name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Setup cache
        uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-new-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-new-

      - name: Install
        run: |
          pip install --upgrade pip==20.1.1
          pip install -r requirements.txt

      - name: Test python code
        run: pytest -vvv -s

      - name: Save Coverage
        run: |
          mkdir -p /tmp/coverage-reports
          mv ./coverage.xml /tmp/coverage-reports/${{ matrix.component }}-coverage.xml
          mv ./junit/junit.xml /tmp/coverage-reports/${{ matrix.component }}-junit.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Coverage Reports
          path: /tmp/coverage-reports

  upload-coverage-reports:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v1
        with:
          name: Coverage Reports
          path: /tmp/coverage-reports

      - name: Copy Coverage Reports
        run: cp /tmp/coverage-reports/*.xml .

      - uses: codecov/codecov-action@v1
        with:
          token: 1fe94a26-7703-4553-b7fc-1e4b73316960
          fail_ci_if_error: false

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: 'x64'

      - name: Build Docs
        run: make docs
